### ISSUE TITLE
Error after submitting of the registrationform (TYPO3 7)

### ISSUE THREAD

**Issue by sarahhoppe** [DMKEBUSINESSGMBH/typo3-t3users#4]
After submitting of the registrationform the following error occurs:
`UNCAUGHT EXCEPTION FOR VIEW: tx_mkforms_util_Runnable Class path not found: /var/www/html/htdocs/typo3/sysext/saltedpasswords/salts/md5/class.tx_saltedpasswords_salts_md5.php`
saltedpassword has been refactored and the paths are no longer correct in TYPO3 7.

**Comment by rengaw83** [comment]
This is not a problem of t3users or saltedpasswords but of your configuration.
Check the extension configuration via the extension manager and save it. The right hashing method depending on your typo3 version will be written to the extension config and you are done
